### ISSUE TITLE
Datacamp villa á Arch

### ISSUE THREAD

**Issue by benediktmag** [edbook/haskoli-islands#23]
Á Arch/Manjaro kemur:
Extension error (datacamp.datacamp):
Handler <function append_datacamp_hidden at 0x7f70acabb160> for event 'doctree-resolved' threw an exception (exception: '/home/bsm/github/haskoli-islands/src/projects/R_fra_grunni/kafli01.rst')
make: *** [Makefile:56: html] Error 2

þegar datacamp er notað. 
Virkar á Windows :/

**Comment by busla** [comment]
þegar þú reynir að builda?

**Comment by benediktmag** [comment]
Já

Benedikt Magnússon

________________________________

**Comment by busla** [comment]
buildar fínt hjá mér (Ubuntu), ertu að nota Makefile-inn í rótinni og argument skv Readme?

**Comment by benediktmag** [comment]
Bara make html í R möppunni. Prófa hitt

Benedikt Magnússon

________________________________

**Comment by busla** [comment]
gera líka `poetry install` eftir að þú pullar main.

**Comment by benediktmag** [comment]
make autobuild í rótinni virkar, veit ekki hvað veldur því að þetta virkar ekki í möppunni sjálfri

**Comment by busla** [comment]
Með því að hafa sameiginlegan entrypoint inn í projectin verður auðveldara að eiga við sameiginleg dependencies (extensions).

Þannig getum við þróað make, build og deploy tólin allveg frá source kóðanum.

Þarna er eitthvað ves með hvernig R_fra_grunni sækir datacamp extensionið (og líklega öll extensions) þegar reynt er að builda úr project möppunni.

Ég skal kíkja á þetta, en við ættum kannski að ákveða hvort þetta eigi að vera möguleiki, að invoke-a skipanir beint úr project möppunni í stað þess að nota alltaf make/cli interface-ið sem við höldum áfram að besta?

**Comment by busla** [comment]
Tek eftir því að `-b dirhtml` virkar en ekki `-b html`.

**Comment by busla** [comment]
Ok, skil ekki hvað þetta er að gera í src kóðanum í datacamp extension-inu en ég ætla að taka þetta út.

https://github.com/edbook/haskoli-islands/blob/main/src/extensions/datacamp-extension/datacamp/datacamp.py#L64-L65

**Comment by busla** [comment]
Nei ok, fann villuna.

`-b dirhtml` virkaði án vandamála vegna þess að þá var sleppt því að embedd-a _Datacamp_ extensioninu 😄 

Villan er hér:
https://github.com/edbook/haskoli-islands/blob/main/src/extensions/datacamp-extension/datacamp/datacamp.py#L69


Það er verið að pilla út `kafli01.rst` frá absolute path en gert ráð fyrir að þetta keyri á Windows og reynt að splitta absolute path á strengnum með `\\` í stað þess að nota python lib sem kann það þvert á OS.

Leysti þetta svona:
```python
from pathlib import Path
...

current_file = Path(section.__dict__["source"]).name
```
