### ISSUE TITLE
vantar forsíðuna í repo?

### ISSUE THREAD

**Issue by busla** [edbook/haskoli-islands#6]
Getur verið að það sé ekki búið að commit-a forsíðunni inn?

![image](https://user-images.githubusercontent.com/3162968/125001000-2dc03780-e041-11eb-8d14-2a330d1cd93f.png)

**Comment by benediktmag** [comment]
Já. Þarf að taka til í henni. Svo innihélt hún smá html-edit sem væri gott að losna við

Benedikt Magnússon

________________________________
From: Jón Levy ***@***.***>
Sent: Thursday, July 8, 2021 11:07:04 PM
To: edbook/haskoli-islands ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [edbook/haskoli-islands] vantar forsíðuna í repo? (#6)


Getur verið að það sé ekki búið að commit-a forsíðunni inn?

[image]<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F3162968%2F125001000-2dc03780-e041-11eb-8d14-2a330d1cd93f.png&data=04%7C01%7Cbsm%40hi.is%7Cb9279ca78d404561908608d942651d5f%7C09fa5f0e211846568529677ed8fdbe78%7C0%7C0%7C637613824320410047%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=95%2Br%2FyAmmx9NW5AinFWyHun8p4E8CtEpTqkjd619KpA%3D&reserved=0>

**Comment by busla** [comment]
Ok, gerum hana kannski að _main project_ með `conf.py` sem child projects erfa svo t.d. með 

```python
from default_config import *
```

Þá getum við build-að allt eða stakt project án þess að vera með duplicate configs.

**Comment by busla** [comment]
ok, getum núna importað extensions svona:

![image](https://user-images.githubusercontent.com/3162968/125006904-b5f90980-e04e-11eb-8dec-144ca80f0382.png)

**Comment by benediktmag** [comment]
Komið
https://github.com/edbook/haskoli-islands/projects/forsida
